export const CREATE_ONE_OF_CUSTOMER_REQUEST = "CREATE_ONE_OF_CUSTOMER_REQUEST";
export const CREATE_ONE_OF_CUSTOMER_SUCCES = "CREATE_ONE_OF_CUSTOMER_SUCCESS";
export const CREATE_ONE_OF_CUSTOMER_FAIL = "CREATE_ONE_OF_CUSTOMER_FAIL";
