export const CREATE_ONE_OF_CUSTOMER_REQUEST = "CREATE_ONE_OF_CUSTOMER_REQUEST";
export const CREATE_ONE_OF_CUSTOMER_SUCCES = "CREATE_ONE_OF_CUSTOMER_SUCCESS";
export const CREATE_ONE_OF_CUSTOMER_FAIL = "CREATE_ONE_OF_CUSTOMER_FAIL";

export const GET_CUSTOMER_ORDERS_REQUEST = "GET_CUSTOMER_ORDERS_REQUEST";
export const GET_CUSTOMER_ORDERS_SUCCESS = "GET_CUSTOMER_ORDERS_SUCCESS";
export const GET_CUSTOMER_ORDERS_FAIL = "GET_CUSTOMER_ORDERS_FAIL";

export const CLEAR_CUSTOMER_ERROR = "CLEAR_CUSTOMER_ERROR";
