export const CREATE_ONE_OF_CUSTOMER_REQUEST = "CREATE_ONE_OF_CUSTOMER_REQUEST";
export const CREATE_ONE_OF_CUSTOMER_SUCCES = "CREATE_ONE_OF_CUSTOMER_SUCCESS";
export const CREATE_ONE_OF_CUSTOMER_FAIL = "CREATE_ONE_OF_CUSTOMER_FAIL";

export const FETCH_CUSTOMER_REQUEST = "FETCH_CUSTOMER_REQUEST";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS ";
export const FECTH_CUSTOMER_FAIL = "FECTH_CUSTOMER_FAIL";
