export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const FETCH_SINGLE_ORDER_REQUEST = 'FETCH_SINGLE_ORDER_REQUEST';
export const FETCH_SINGLE_ORDER_SUCCESS = 'FETCH_SINGLE_ORDER_SUCCESS';
export const FETCH_SINGLE_ORDER_FAIL = 'FETCH_SINGLE_ORDER_FAIL';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST ';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';

export const FETCH_ORDER_STATS_REQUEST = 'FETCH_ORDER_STATS_REQUEST';
export const FETCH_ORDER_STATS_SUCCESS = 'FETCH_ORDER_STATS_SUCCESS';
export const FETCH_ORDER_STATS_FAIL = 'FETCH_ORDER_STATS_FAIL';

export const CONFIRM_ORDER_REQUEST = 'CONFIRM_ORDER_REQUEST';
export const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS';
export const CONFIRM_ORDER_FAIL = 'CONFIRM_ORDER_FAIL';
