export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT = "LOGOUT";
export const RESTORE_TOKEN = "RESTORE_TOKEN";

export const GET_DISTRIBUTOR_CUSTOMERS_REQUEST =
  "GET_DISTRIBUTOR_CUSTOMERS_REQUEST";
export const GET_DISTRIBUTOR_CUSTOMERS_SUCCESS =
  "GET_DISTRIBUTOR_CUSTOMERS_SUCCESS";
export const GET_DISTRIBUTOR_CUSTOMERS_FAIL = "GET_DISTRIBUTOR_CUSTOMERS_FAIL";
