export const FETCH_INVENTORY_REQUEST = "FETCH_INVENTORY_REQUEST";
export const FETCH_INVENTORY_SUCCESS = "FETCH_INVENTORY_SUCCESS";
export const FETCH_INVENTORY_FAIL = "FETCH_INVENTORY_FAIL";

export const UPDATE_INVENTORY_REQUEST = "UPDATE_INVENTORY_REQUEST";
export const UPDATE_INVENTORY_SUCCESS = "UPDATE_INVENTORY_SUCCESS";
export const UPDATE_INVENTORY_FAIL = "UPDATE_INVENTORY_FAIL";

export const CONFIRM_VAN_SALES_REQUEST = "CONFIRM_VAN_SALES_REQUEST";
export const CONFIRM_VAN_SALES_SUCCESS = "CONFIRM_VAN_SALES_SUCCESS";
export const CONFIRM_VAN_SALES_FAIL = "CONFIRM_VAN_SALES_FAIL";

export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const INCREMENT_QUANTITY_TYPING = "INCREMENT_QUANTITY_TYPING";

export const RETURN_PRODUCTS_REQUEST = "RETURN_PRODUCTS_REQUEST";
export const RETURN_PRODUCTS_SUCCESS = "RETURN_PRODUCTS_SUCCESS";
export const RETURN_PRODUCTS_FAIL = "RETURN_PRODUCTS_FAIL";

export const VAN_POST_EMPTIES = "VAN_POST_EMPTIES";

export const GET_VAN_EMPTIES_SUCCESS = "GET_VAN_EMPTIES_SUCCESS";
export const GET_VAN_EMPTIES_REQUEST = "GET_VAN_EMPTIES_REQUEST";
export const GET_VAN_EMPTIES_FAIL = "GET_VAN_EMPTIES_FAIL";

export const RETURN_VAN_EMPTIES_SUCCESS = "RETURN_VAN_EMPTIES_SUCCESS";
export const RETURN_VAN_EMPTIES_REQUEST = "RETURN_VAN_EMPTIES_REQUEST";
export const RETURN_VAN_EMPTIES_FAIL = "RETURN_VAN_EMPTIES_FAIL";

export const UPDATE_CUSTOMER_STATUS = "UPDATE_CUSTOMER_STATUS";
