const Routes = {
  DELIVERIES_SCREEN: "Deliveries",
  PRODUCTS_SCREEN: "Products",
  CUSTOMERS_SCREEN: "Customers",
  HOME_SCREEN: "HomeScreen",
  WELCOME_SCREEN: "Welcome",
  LOGOUT_SCREEN: "Logout",
  NOTIFICATIONS_SCREEN: "Notifications",
  DELIVERIES_DETAILS_SCREEN: "DeliveryDetails",
  GENERATE_INVOICE_SCREEN: "GenerateInvoice",
  CUSTOMER_DETAILS_SCREEN: "CustomerDetails",
  SELLTO_CUSTOMER_SCREEN: "SellToCustomer",
  VANINVOICE_SCREEN: "VanInvoice",
  ADDCUSTOMER_SCREEN: "AddCustomer",
  ONEOF_SALE_SCREEN: "OneOfSale",
  ONEOF_SALEINVOINCE_SCREEN: "SalesInvoice",
  ALLPRODUCTS_SCREEN: "AllProducts",
  LIQUIDEMPTYPRODUCTS_SCREEN: "LiquidEmptyProducts",
  LOGIN_SCREEN: "Login",
  CONTINUE_SCREEN: "Continue",
  LOGIN_ERROR: "LoginError",
  WELCOME_ERROR: "WelcomeError",
};

export default Routes;
