const Routes = {
  DELIVERIES_SCREEN: "Deliveries",
  PRODUCTS_SCREEN: "Products",
  CUSTOMERS_SCREEN: "Customers",
  HOME_SCREEN: "HomeScreen",
  WELCOME_SCREEN: "Welcome",
  NOTIFICATIONS_SCREEN: "Notifications",
  DELIVERIES_DETAILS_SCREEN: "DeliveryDetails",
  GENERATE_INVOICE_SCREEN: "GenerateInvoice",
  CUSTOMER_DETAILS_SCREEN: "CustomerDetails",
  SELLTO_CUSTOMER_SCREEN: "SellToCustomer",
  VANINVOICE_SCREEN: "VanInvoice",
  ADDCUSTOMER_SCREEN: "AddCustomer",
  ONEOF_SALE_SCREEN: "OneOfSale",
  ONEOF_SALEINVOINCE_SCREEN: "SalesInvoice",
  ALLPRODUCTS_SCREEN: "AllProducts",
  LIQUIDEMPTYPRODUCTS_SCREEN: "LiquidEmptyProducts",
  CONTINUE_SCREEN: "Continue",
  CUSTOMERS_SCREEN_UGANGA: "CustomerUganda",
  SELLTO_CUSTOMER_SCREEN_UGANDA: "SellToCustomerUganda",
  GENERATE_INVOICE_SCREEN_UGANGA: "InvoiceUganda",
  INVOICE_SCREEN: "InvoiceScreen",
  CUSTOMER_DETAILS_SCREEN_UGANDA: "CustomerDetailsUganda",
  SELLTO_ONEOF_CUSTOMER_UGANDA: "SellToOneCustomerUganda",
  ONEOF_INVOICE_UGANDA: "OneOfInvoiceUganda",
};

export default Routes;
